# baseURL = "https://thomasdylandaniel.press"
relativeURLs = true
languageCode = "en-us"
title = "Author Bio & Press Site for Thomas Dylan Daniel"
theme = "ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/tdylandaniel/"
  twitter = "https://twitter.com/theiriginal"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/StrummerMural.jpg"
  recent_posts_number = 2

  [[menu.main]]
      name = "Home" #Name in the navigation bar
      weight = 10 #The larger the weight, the more on the right this item will be
      url = "/" #URL address
